blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from blogapp.api_views import CategoryViewSet, PostViewSet, TagViewSet

# router = routers.DefaultRouter()
# router.register(r'categories', CategoryViewSet)
#
# router_p = routers.DefaultRouter()
# router_p.register(r'posts', PostViewSet)

router = routers.DefaultRouter()
router.register(r'categories', CategoryViewSet)
router.register(r'posts', PostViewSet)
router.register(r'tags', TagViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls', namespace='blog')),
    path('users/', include('usersapp.urls', namespace='users')),
    path('api-auth/', include('rest_framework.urls')),
    # path('api/v0/categories/', include(router.urls)),
    # path('api/v0/posts/', include(router_p.urls)),
    path('api/v0/', include(router.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

blog/blogapp/urls.py
from django.urls import path
from blogapp import views


app_name = 'blogapp'

urlpatterns = [
    path('', views.main_view, name='index'),
    path('contact/', views.contact_view, name='contact'),
    path('create/', views.create_post, name='create'),
    path('post/<int:id>/', views.post, name='post'),
    path('tag-list', views.TagListView.as_view(), name='tag_list'),
    path('tag-detail/<int:pk>/', views.TagDetailView.as_view(), name='tag_detail'),
    path('tag-create/', views.TagCreateView.as_view(), name='tag_create'),
    path('tag-update/<int:pk>/', views.TagUpdataView.as_view(), name='tag_update'),
    path('tag-delete/<int:pk>/', views.TagDeleteView.as_view(), name='tag_delete'),

    path('category-detail/<int:pk>/', views.CategoryDetailView.as_view(), name='category_detail'),
    path('post-category-create/<int:pk>', views.PostCategoryCreateView.as_view(), name='post_category_create'),
    path('simple/', views.SimpleMainAjax.as_view(), name='simple_ajax'),
]

blog/blogapp/models.py
from django.db import models
from django.db.models import F
from django.utils.functional import cached_property

from usersapp.models import BlogUser


# 3 типа наследования: abstract, классическое, proxy
class ActiveManager(models.Manager):

    def get_queryset(self):
        all_objects = super().get_queryset()
        return all_objects.filter(is_active=True)


class IsActiveMixin(models.Model):
    objects = models.Manager()
    active_objects = ActiveManager()
    is_active = models.BooleanField(default=False)

    class Meta:
        abstract = True


class UpdatedObjectsManager(models.Manager):

    def get_queryset(self):
        all_objects = super().get_queryset()
        # Дата обновления не равна дата содания F - запрос
        return all_objects.filter(update=F('create'))


class TimeStamp(models.Model):
    """
    Abstract - для нее не создаются новые таблицы
    данные хранятся в каждом наследнике
    """
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True, db_index=True)

    class Meta:
        abstract = True


# Create your models here.
class Category(TimeStamp):
    # Id не надо, он уже сам появиться
    name = models.CharField(max_length=16, unique=True, verbose_name='Name')
    description = models.TextField(blank=True, verbose_name='Desc')

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    # Основные типы полей
    # дата
    # models.DateField
    # models.DateTimeField
    # models.TimeField
    # # Числа
    # models.IntegerField
    # models.PositiveIntegerField
    # models.PositiveSmallIntegerField
    # models.FloatField
    # models.DecimalField
    # # Логический
    # models.BooleanField
    # # Байты (blob)
    # models.BinaryField
    # # Картинка
    # models.ImageField
    # # Файл
    # models.FileField
    # # url, email
    # models.URLField
    # models.EmailField

    def __str__(self):
        return self.name


class Tag(IsActiveMixin):
    name = models.CharField(max_length=16, unique=True)

    def __str__(self):
        return self.name


class Post(TimeStamp, IsActiveMixin):
    name = models.CharField(max_length=32, unique=True)
    text = models.TextField()
    # Связь с категорией
    # один - много
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category_posts')
    # Связь с тегом
    tags = models.ManyToManyField(Tag)
    # Картинка
    # 2 варианта хранения кратинки (1 - в базе, 2 - на диске)
    image = models.ImageField(upload_to='posts', null=True, blank=True)
    user = models.ForeignKey(BlogUser, on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(default=1)

    @cached_property
    def get_all_tags(self):
        tags = Tag.objects.all()
        return tags

    def has_image(self):
        # print('my image:', self.image)
        # print('type', type(self.image))
        return bool(self.image)

    def some_method(self):
        return 'hello from method'

    def __str__(self):
        return f'{self.name}, category: {self.category.name}'

    def display_tags(self):
        tags = self.tags.all()
        result = ';'.join([item.name for item in tags])
        return result


# Класское наследование
class CoreObject(models.Model):
    name = models.CharField(max_length=32)


class Car(CoreObject):
    # является
    description = models.TextField()


class Toy(CoreObject):
    text = models.TextField()

blog/blogapp/forms.py
from django import forms
from .models import Post
from .models import Tag


class ContactForm(forms.Form):
    name = forms.CharField(label='Название')
    email = forms.EmailField(label='email')
    message = forms.CharField(label='Сообщение')


class PostForm(forms.ModelForm):
    name = forms.CharField(label='Название',
                           widget=forms.TextInput(attrs={'placeholder': 'Name', 'class': 'form-control'}))

    # Чекбоксы
    tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(),
                                          widget=forms.CheckboxSelectMultiple())

    class Meta:
        model = Post
        # fields = '__all__'
        # fields = ('name', 'category')
        exclude = ('user',)


class PostCategoryForm(forms.ModelForm):
    name = forms.CharField(label='Название',
                           widget=forms.TextInput(attrs={'placeholder': 'Name', 'class': 'form-control'}))

    # Чекбоксы
    tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(),
                                          widget=forms.CheckboxSelectMultiple())

    class Meta:
        model = Post
        # fields = '__all__'
        # fields = ('name', 'category')
        exclude = ('user', 'category')

blog/blogapp/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from django.views.generic.base import ContextMixin

from .models import Post, Tag, Category
from .forms import ContactForm, PostForm, PostCategoryForm
from django.core.mail import send_mail
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.
def main_view(request):
    # posts = Post.objects.filter(is_active=True)
    posts = Post.active_objects.select_related('category', 'user').all()
    # posts = Post.active_objects.all()
    paginator = Paginator(posts, 500)

    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        posts = paginator.page(paginator.num_pages)

    title = 'главная страница'
    # title = title.capitalize()
    return render(request, 'blogapp/index.html', context={'posts': posts, 'title': title})


def contact_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            # Получить данные из форы
            name = form.cleaned_data['name']
            message = form.cleaned_data['message']
            email = form.cleaned_data['email']

            send_mail(
                'Contact message',
                f'Ваш сообщение {message} принято',
                'from@example.com',
                [email],
                fail_silently=True,
            )
            return HttpResponseRedirect(reverse('blog:index'))
        else:
            return render(request, 'blogapp/contact.html', context={'form': form})
    else:
        form = ContactForm()
        return render(request, 'blogapp/contact.html', context={'form': form})


# можт читать только админ
@user_passes_test(lambda u: u.is_superuser)
def post(request, id):
    post = get_object_or_404(Post, id=id)

    all_tags = post.get_all_tags
    for item in all_tags:
        print(item)
    # добавим набор всех тегов
    return render(request, 'blogapp/post.html', context={'post': post})


@login_required
def create_post(request):
    if request.method == 'GET':
        form = PostForm()
        return render(request, 'blogapp/create.html', context={'form': form})
    else:
        form = PostForm(request.POST, files=request.FILES)
        if form.is_valid():
            # Добавить в форму текущего пользователя request.user - текущий пользователь
            form.instance.user = request.user
            form.save()
            return HttpResponseRedirect(reverse('blog:index'))
        else:
            return render(request, 'blogapp/create.html', context={'form': form})


class NameContextMixin(ContextMixin):

    def get_context_data(self, *args, **kwargs):
        """
        Отвечает за передачу параметров в контекст
        :param args:
        :param kwargs:
        :return:
        """
        context = super().get_context_data(*args, **kwargs)
        context['name'] = 'Теги'
        return context


# CRUD CREATE, READ (LIST, DETAIL), UPDATE, DELETE
# список тегов
class TagListView(ListView, NameContextMixin):
    model = Tag
    template_name = 'blogapp/tag_list.html'
    context_object_name = 'tags'
    paginate_by = 5

    def get_queryset(self):
        """
        Получение данных
        :return:
        """
        return Tag.active_objects.all()


# детальная информация
class TagDetailView(UserPassesTestMixin, DetailView, NameContextMixin):
    model = Tag
    template_name = 'blogapp/tag_detail.html'
    raise_exception = False

    def test_func(self):
        return self.request.user.is_superuser

    def get(self, request, *args, **kwargs):
        """
        Метод обработки get запроса
        :param request:
        :param args:
        :param kwargs:
        :return:
        """
        self.tag_id = kwargs['pk']
        return super().get(request, *args, **kwargs)

    def get_object(self, queryset=None):
        """
        Получение этого объекта
        :param queryset:
        :return:
        """
        return get_object_or_404(Tag, pk=self.tag_id)


# создание тега
# Важно LoginRequiredMixin - он должен идти 1-ым
class TagCreateView(LoginRequiredMixin, CreateView, NameContextMixin):
    # form_class =
    fields = '__all__'
    model = Tag
    success_url = reverse_lazy('blog:tag_list')
    template_name = 'blogapp/tag_create.html'

    def post(self, request, *args, **kwargs):
        """
        Пришел пост запрос
        :param request:
        :param args:
        :param kwargs:
        :return:
        """
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        """
        Метод срабатывает после того как форма валидна
        :param form:
        :return:
        """
        # self.request.user - текущий пользователь
        # form.instance.user = self.request.user
        return super().form_valid(form)


class TagUpdataView(UpdateView):
    fields = '__all__'
    model = Tag
    success_url = reverse_lazy('blog:tag_list')
    template_name = 'blogapp/tag_create.html'


class TagDeleteView(DeleteView):
    template_name = 'blogapp/tag_delete_confirm.html'
    model = Tag
    success_url = reverse_lazy('blog:tag_list')


class CategoryDetailView(DetailView):
    template_name = 'blogapp/category_detail.html'
    model = Category

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = PostCategoryForm()
        return context


class PostCategoryCreateView(CreateView):
    model = Post
    template_name = 'blogapp/category_detail.html'
    success_url = reverse_lazy('')
    form_class = PostCategoryForm

    def post(self, request, *args, **kwargs):
        self.category_pk = kwargs['pk']
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        user = self.request.user
        form.instance.user = user
        category = get_object_or_404(Category, pk=self.category_pk)
        form.instance.category = category
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:category_detail', kwargs={'pk': self.category_pk})


class SimpleMainAjax(TemplateView):
    template_name = 'blogapp/simple.html'

blog/blogapp/templates/blogapp/category_detail.html
{% extends "base.html" %}

{% block title %}
{% endblock%}

{% block content %}
<div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
        <h1>{{object.name}}</h1>
        {% for post in object.category_posts.all %}
        {{ post.name }}
        <p></p>
        <hr>
        {% endfor %}

        <form method="post" action="{% url 'blog:post_category_create' pk=object.pk %}">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit">Сохранить</button>
        </form>
    </div>


</div>
{% endblock %}

blog/blogapp/templates/blogapp/contact.html
{% extends "base.html" %}

{% block title %}
Создание поста
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
        <p>Want to get in touch? Fill out the form below to send me a message and I will get back to you as soon as
            possible!</p>
        <!-- Contact Form - Enter your email address on line 19 of the mail/contact_me.php file to make this form work. -->
        <!-- WARNING: Some web hosts do not allow emails to be sent through forms to common mail hosts like Gmail or Yahoo. It's recommended that you use a private domain email address! -->
        <!-- To use the contact form, your site must be on a live web host with PHP! The form will not work locally! -->
        <form method="post" id="contactForm">
            {% csrf_token %}
            {{ form.as_ul }}
            <button type="submit" class="btn btn-primary" id="sendMessageButton">Send</button>

        </form>
    </div>
</div>
{% endblock %}

blog/blogapp/templates/blogapp/create.html
{% extends "base.html" %}

{% block title %}
Создание поста
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {# form.as_ul #}
            {% for field in form %}
            <p>{{field.label_tag}}</p>
            <hr>
            {% for error in field.errors %}
            {{error}}
            {% endfor %}
            <p>{{field}}</p>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </form>
    </div>
</div>
{% endblock %}

blog/blogapp/templates/blogapp/index.html
{% extends "base.html" %}

{% block title %}
Главная
{% endblock %}

{% block content %}
<div class="row">
    Количество постов на странице: {{posts|length}}
    <div class="col-lg-8 col-md-10 mx-auto">
        {% for item in posts %}
        <div class="post-preview">
            <a href="{% url 'blog:post' id=item.id %}">
                <h2 class="post-title">
                    {{ item.name }}
                </h2>
                <h3 class="post-subtitle">
                    Описание ({{item.category.name}}) ({{item.user.username}})
                </h3>
            </a>
            <p class="post-meta">Posted by
                <a href="#">Start Bootstrap</a>
                on September 24, 2019.
                {% if item.has_image %}
                Есть картинка
                {% else%}
                Нет картинки
                {% endif %}
                {{item.has_image}}
                {{item.some_method}}
            </p>
        </div>
        <hr>
        {% endfor %}
        <!-- Pager -->

        <div class="clearfix">
            <div class="pagination">

            <span class="step-links">
                {% if posts.has_previous %}
                    <a href="?page={{ posts.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
                </span>

                {% if posts.has_next %}
{#               <a href="?page={{ posts.next_page_number }}">next</a> #}


                    <a class="btn btn-primary float-right"
                       href="?page={{ posts.next_page_number }}">Older Posts &rarr;</a>

                {% endif %}


            </span>
            </div>
        </div>

    </div>
</div>
{% endblock %}

blog/blogapp/templates/blogapp/post.html
{% extends "base.html" %}

{% block title %}
{{post.name}}
{% endblock%}

{% block content %}
<div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">

        {% with all_tags=post.get_all_tags %}

            {% for tag in all_tags %}
            {{tag}}//
            {% endfor %}
            <p></p>
            <hr>
            {% if post.image %}
            <img src="{{post.image.url}}" width="300">
            {% endif %}
            {{post.text|safe}}
            <p></p>
            <hr>
            {% for tag in all_tags %}
            {{tag}}--
            {% endfor %}

        {% endwith %}
    </div>
</div>
{% endblock %}

blog/blogapp/templates/blogapp/simple.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Empty</title>
</head>
<body>
    <button type="button" id="categories">Категории</button>
    <button type="button" id="posts">Посты</button>
    <button type="button" id="all">Все</button>

    <ul id="div_categories"></ul>
    <hr>
    <ol id="div_posts"></ol>

<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'js/my.js' %}"></script>

</body>
</html>

blog/blogapp/templates/blogapp/tag_create.html
{% extends "base.html" %}

{% block title %}
Создание тега
{% endblock %}

{% block content %}
<div class="row">
    <h1>{{name}}</h1>
    <div class="col-lg-8 col-md-10 mx-auto">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </form>
    </div>
</div>
{% endblock %}

blog/blogapp/templates/blogapp/tag_delete_confirm.html
{% extends "base.html" %}

{% block title %}
{{object.name}}
{% endblock%}

{% block content %}
<div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
        {{object.name}}
    </div>

    Вы уверены?
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Да</button>
    </form>
</div>
{% endblock %}

blog/blogapp/templates/blogapp/tag_detail.html
{% extends "base.html" %}

{% block title %}
{{post.name}}
{% endblock%}

{% block content %}
<div class="row">
    <h1>{{name}}</h1>
    <div class="col-lg-8 col-md-10 mx-auto">
        {{object.name}}
    </div>

    <a href="{% url 'blog:tag_update' pk=object.pk %}">
            Изменить
        </a>
</div>
{% endblock %}

blog/blogapp/templates/blogapp/tag_list.html
{% extends "base.html" %}

{% block title %}
Список тегов
{% endblock %}

{% block content %}
<h1>{{name}}</h1>
<ul>
    {% for item in tags %}
    <li>
        <a href="{% url 'blog:tag_detail' pk=item.pk %}">
            {{item.name}}
        </a>
/
        <a href="{% url 'blog:tag_update' pk=item.pk %}">
            Изменить
        </a>
        /
        <a href="{% url 'blog:tag_delete' pk=item.pk %}">
            Удалить
        </a>

    </li>
    {% endfor %}

    <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>


    <a href="{% url 'blog:tag_create' %}">Создать</a>
</ul>
{% endblock %}